import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import DisplayCenter from '../components/DisplayCenter'
import DisplayRight from '../components/DisplayRight'
import DisplayLeft from '../components/DisplayLeft'

// components
import NavBar from '../components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles['main']}>

        <NavBar/>

        <main className='w-screen flex flex-row mt-9'>
          <DisplayLeft />
          <DisplayCenter />
          <DisplayRight />
        </main>
      </div>
    </>
  )
}
